name: Deploy Vue App to Firebase

on:
  push:
    branches:
      - master  # Change this if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4) Build the Vue app
      - name: Build Vue App
        run: npm run build

      # 5) Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.4.0
        with:
          # Point at your Firebase project ID
          args: deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          # Make sure you’ve stored a valid token in your repo’s secrets
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
