name: Deploy Vue App to Firebase

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5. Build the Vue app
      - name: Build Vue App
        run: npm run build

      # 6. Install Functions dependencies
      - name: Install Functions Dependencies
        run: npm ci
        working-directory: ./functions

      # 7. Deploy to Firebase Hosting and Functions
      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }} --debug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
