name: Deploy Vite App to Firebase

on:
  push:
    branches:
      - main   # or your deploy branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5. Verify Firebase CLI
      - name: Check Firebase CLI Version
        run: firebase --version

      # 6. Debug environment
      - name: Debug Env Vars
        run: |
          echo "Project ID: ${{ secrets.FIREBASE_PROJECT_ID }}"
          echo "Deploy Token: ${{ secrets.FIREBASE_DEPLOY_TOKEN != '' }}"
          echo "VITE_FIREBASE_API_KEY:    ${{ secrets.VITE_FIREBASE_API_KEY != '' }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

      # 7. Build the Vite app
      - name: Build Vite App
        env:
          VITE_FIREBASE_API_KEY:        ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN:    ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID:     ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID:        ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
        run: npm run build

      # 8. Deploy to Firebase Hosting
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }} --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}